# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Antonella Barisic
tagline:          'R&D engineer in AI Robotics'
description:      'Robotics<br/>
& Computer Vision.'
url:              http://antonellabarisic.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://antonellabarisic.github.io/

plugins: [jekyll-paginate, jekyll-gist]

